#!/bin/bash

######################

BIGTESTORDER=osuvpywthx

THIS_PROJECT=sa

TEMP=$1

declare -A names

names["al"]="*-altpath"
names["hi"]="*-hints"
names["nm"]="*-nudmis"
names["sl"]="*-slider"
names["ve"]="*-verbs"
names["mi"]="*-min"
names["ma"]="*-max"

names["d"]=demo-dome
names["h"]=others
names["o"]=ordeal-reload
names["s"]=stores
names["t"]=otters
names["u"]=routes
names["v"]=troves
names["p"]=presto
names["w"]=towers
names["y"]=oyster
names["x"]=lone
names["l"]=lone

. ./sts
