#!/bin/bash

######################

BIGTESTORDER=osfimrx

THIS_PROJECT=sa

TEMP=$1

declare -A names

names["de"]="*-detail"
names["hi"]="*-hints"
names["ma"]="*-max"
names["mi"]="*-min"
names["nm"]="*-nudmis"

names["f"]=forest
names["o"]=ordeal-loader
names["i"]=sortie
names["m"]=metros
names["r"]=resort
names["s"]=stores
names["x"]=lone
names["l"]=lone

. ./sts
